# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartmodel_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=2),
        ),
    ]
