# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201026_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Large', 'L'), ('Medium', 'M'), ('XtraLarge', 'XL'), ('XtraXtraLarge', 'XXL')], default='S', max_length=10),
        ),
    ]
