# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
    ]
